# config/services_evsourcing.yaml
services:

    # Default values for the services of this file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Connection to AMQP queue system (RabbitMQ)
    amqp.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments:
            $host:     '%env(AMQP_HOST)%'
            $port:     '%env(AMQP_PORT)%'
            $user:     '%env(AMQP_USER)%'
            $password: '%env(AMQP_PASSWORD)%'
            $vhost:    '%env(AMQP_VHOST)%'
        public: true

    amqp.configurator:
        class: Davamigo\Infrastructure\Core\Helpers\AmqpConfigurator

    # MongoDB client
    mongodb.client:
        class: MongoDB\Client
        arguments:
            $uri: 'mongodb://%env(MONGODB_HOST)%:%env(MONGODB_PORT)%/'
        public: true

    mongodb.configurator:
        class: Davamigo\Infrastructure\Core\Helpers\MongoDBConfigurator

    # Event sourcing: command bus
    event_sourcing.command_handler_collection:
        class: Davamigo\Domain\Core\CommandHandler\CommandHandlerCollection
        arguments: [ !tagged event_sourcing.command_handler]

    event_sourcing.command_bus:
        class: Davamigo\Infrastructure\Core\CommandBus\InstantCommandBus
        arguments:
            $handlers: '@event_sourcing.command_handler_collection'
        public: true

    # Event sourcing: event bus
    event_sourcing.event_bus:
        class: Davamigo\Infrastructure\Core\EventBus\AmqpEventBus
        public: true

    # Event sourcing: event consumer
    event_sourcing.event_collection:
        class: Davamigo\Domain\Core\Event\EventCollection
        arguments: [ !tagged event_sourcing.event]

    event_sourcing.event_consumer:
        class: Davamigo\Infrastructure\Core\EventConsumer\AmqpEventConsumer
        arguments:
            $events: '@event_sourcing.event_collection'
        public: true

    # Event sourcing: event storage
    event_sourcing.event_storage.mongodb:
        class: Davamigo\Infrastructure\Core\EventStorage\MongoDBEventStorage

    event_sourcing.event_storage.doctrine:
        class: Davamigo\Infrastructure\Core\EventStorage\DoctrineEventStorage

    # Event sourcing: entity projector
    event_sourcing.entity_projector:
        class: Davamigo\Infrastructure\Core\EntityProjector\MongoDBEntityProjector
        arguments:
            $events: '@event_sourcing.event_collection'
        public: true

    # Service aliases for autowiring
    MongoDB\Client: '@mongodb.client'
    PhpAmqpLib\Connection\AMQPStreamConnection: '@amqp.connection'
    Davamigo\Domain\Core\CommandBus\CommandBus: '@event_sourcing.command_bus'
    Davamigo\Domain\Core\EventBus\EventBus: '@event_sourcing.event_bus'
    Davamigo\Domain\Core\EventConsumer\EventConsumer: '@event_sourcing.event_consumer'
    Davamigo\Domain\Core\EntityProjector\EntityProjector: '@event_sourcing.entity_projector'
    Davamigo\Infrastructure\Core\EventStorage\MongoDBEventStorage: '@event_sourcing.event_storage.mongodb'
    Davamigo\Infrastructure\Core\EventStorage\DoctrineEventStorage: '@event_sourcing.event_storage.doctrine'
    Davamigo\Infrastructure\Core\Helpers\AmqpConfigurator: '@amqp.configurator'
    Davamigo\Infrastructure\Core\Helpers\MongoDBConfigurator: '@mongodb.configurator'
